#spring.application.name=blog-server
server:
  port: 5599
spring:
  datasource:
    password: 12345678
    url: jdbc:mysql://localhost:3306/blog-app
    username: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
